export const europeanCities = [
  // Spanish Cities (Primary Focus)
  'مدريد', 'Madrid',
  'برشلونة', 'Barcelona', 
  'إشبيلية', 'Seville',
  'فالنسيا', 'Valencia',
  'بلباو', 'Bilbao',
  
  // Other Major European Cities
  'باريس', 'Paris',
  'لندن', 'London',
  'روما', 'Rome',
  'برلين', 'Berlin',
  'أمستردام', 'Amsterdam',
  'فيينا', 'Vienna',
  'براغ', 'Prague',
  'بودابست', 'Budapest',
  'وارسو', 'Warsaw',
  'زيورخ', 'Zurich',
  'جنيف', 'Geneva',
  'ميلان', 'Milan',
  'فلورنسا', 'Florence',
  'البندقية', 'Venice',
  'أثينا', 'Athens',
  'لشبونة', 'Lisbon',
  'بورتو', 'Porto',
  'ستوكهولم', 'Stockholm',
  'كوبنهاغن', 'Copenhagen',
  'أوسلو', 'Oslo',
  'هلسنكي', 'Helsinki',
  'بروكسل', 'Brussels',
  'دبلن', 'Dublin',
  'إدنبرة', 'Edinburgh',
  'مانشستر', 'Manchester',
  'ليون', 'Lyon',
  'نيس', 'Nice',
  'مرسيليا', 'Marseille',
  'مونيخ', 'Munich',
  'فرانكفورت', 'Frankfurt',
  'هامبورغ', 'Hamburg',
  'إسطنبول', 'Istanbul'
];

export const europeanCountries = [
  'إسبانيا', 'Spain',
  'فرنسا', 'France', 
  'إيطاليا', 'Italy',
  'ألمانيا', 'Germany',
  'المملكة المتحدة', 'United Kingdom',
  'هولندا', 'Netherlands',
  'النمسا', 'Austria',
  'جمهورية التشيك', 'Czech Republic',
  'المجر', 'Hungary',
  'بولندا', 'Poland',
  'سويسرا', 'Switzerland',
  'اليونان', 'Greece',
  'البرتغال', 'Portugal',
  'السويد', 'Sweden',
  'الدنمارك', 'Denmark',
  'النرويج', 'Norway',
  'فنلندا', 'Finland',
  'بلجيكا', 'Belgium',
  'أيرلندا', 'Ireland',
  'اسكتلندا', 'Scotland',
  'تركيا', 'Turkey'
];
