
export const europeanCities = [
  // Western Europe
  'London', 'لندن',
  'Paris', 'باريس',
  'Berlin', 'برلين',
  'Madrid', 'مدريد',
  'Rome', 'روما',
  'Amsterdam', 'أمستردام',
  'Brussels', 'بروكسل',
  'Vienna', 'فيينا',
  'Zurich', 'زيورخ',
  'Geneva', 'جنيف',
  'Barcelona', 'برشلونة',
  'Milan', 'ميلان',
  'Florence', 'فلورنسا',
  'Venice', 'البندقية',
  'Naples', 'نابولي',
  'Lisbon', 'لشبونة',
  'Porto', 'بورتو',
  'Dublin', 'دبلن',
  'Edinburgh', 'إدنبرة',
  'Manchester', 'مانشستر',
  'Birmingham', 'برمنغهام',
  'Liverpool', 'ليفربول',
  'Glasgow', 'غلاسكو',
  'Lyon', 'ليون',
  'Marseille', 'مرسيليا',
  'Nice', 'نيس',
  'Toulouse', 'تولوز',
  'Strasbourg', 'ستراسبورغ',
  'Munich', 'مونيخ',
  'Frankfurt', 'فرانكفورت',
  'Hamburg', 'هامبورغ',
  'Cologne', 'كولونيا',
  'Stuttgart', 'شتوتغارت',
  'Düsseldorf', 'دوسلدورف',
  
  // Eastern Europe
  'Prague', 'براغ',
  'Budapest', 'بودابست',
  'Warsaw', 'وارسو',
  'Krakow', 'كراكوف',
  'Bucharest', 'بوخارست',
  'Sofia', 'صوفيا',
  'Belgrade', 'بلغراد',
  'Zagreb', 'زغرب',
  'Ljubljana', 'ليوبليانا',
  'Bratislava', 'براتيسلافا',
  'Kiev', 'كييف',
  'Moscow', 'موسكو',
  'St. Petersburg', 'سان بطرسبرغ',
  
  // Northern Europe
  'Stockholm', 'ستوكهولم',
  'Copenhagen', 'كوبنهاغن',
  'Oslo', 'أوسلو',
  'Helsinki', 'هلسنكي',
  'Gothenburg', 'غوتنبرغ',
  'Malmö', 'مالمو',
  'Bergen', 'بيرغن',
  'Trondheim', 'تروندهايم',
  'Aarhus', 'آرهوس',
  'Odense', 'أودنسه',
  'Tampere', 'تامبيري',
  'Turku', 'توركو',
  
  // Southern Europe
  'Athens', 'أثينا',
  'Thessaloniki', 'سالونيكا',
  'Istanbul', 'إسطنبول',
  'Ankara', 'أنقرة',
  'Izmir', 'إزمير',
  'Antalya', 'أنطاليا',
  'Valletta', 'فاليتا',
  'Nicosia', 'نيقوسيا',
  'Limassol', 'ليماسول'
];

export const europeanCurrencies = [
  { code: 'EUR', name: 'Euro', nameAr: 'يورو', symbol: '€' },
  { code: 'GBP', name: 'British Pound', nameAr: 'جنيه إسترليني', symbol: '£' },
  { code: 'CHF', name: 'Swiss Franc', nameAr: 'فرنك سويسري', symbol: 'CHF' },
  { code: 'NOK', name: 'Norwegian Krone', nameAr: 'كرون نرويجي', symbol: 'kr' },
  { code: 'SEK', name: 'Swedish Krona', nameAr: 'كرون سويدي', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', nameAr: 'كرون دنماركي', symbol: 'kr' },
  { code: 'PLN', name: 'Polish Zloty', nameAr: 'زلوتي بولندي', symbol: 'zł' },
  { code: 'CZK', name: 'Czech Koruna', nameAr: 'كرون تشيكي', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint', nameAr: 'فورنت هنغاري', symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu', nameAr: 'ليو روماني', symbol: 'lei' },
  { code: 'BGN', name: 'Bulgarian Lev', nameAr: 'ليف بلغاري', symbol: 'лв' },
  { code: 'HRK', name: 'Croatian Kuna', nameAr: 'كونا كرواتي', symbol: 'kn' },
  { code: 'RSD', name: 'Serbian Dinar', nameAr: 'دينار صربي', symbol: 'RSD' },
  { code: 'RUB', name: 'Russian Ruble', nameAr: 'روبل روسي', symbol: '₽' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', nameAr: 'هريفنيا أوكراني', symbol: '₴' },
  { code: 'TRY', name: 'Turkish Lira', nameAr: 'ليرة تركية', symbol: '₺' }
];

// European Budget Airlines only
export const europeanBudgetAirlines = [
  { code: 'FR', name: 'Ryanair', nameAr: 'رايان إير' },
  { code: 'U2', name: 'EasyJet', nameAr: 'إيزي جيت' },
  { code: 'W6', name: 'Wizz Air', nameAr: 'ويز إير' },
  { code: 'VY', name: 'Vueling', nameAr: 'فويلنغ' },
  { code: 'EW', name: 'Eurowings', nameAr: 'يوروينغز' },
  { code: 'DY', name: 'Norwegian Air', nameAr: 'نورويجيان إير' },
  { code: 'LS', name: 'Jet2', nameAr: 'جيت 2' },
  { code: 'PC', name: 'Pegasus Airlines', nameAr: 'بيغاسوس' }
];
