
export const worldCities = [
  // European Cities (Primary Focus)
  { ar: 'مدريد', en: 'Madrid', code: 'MAD', country: 'Spain' },
  { ar: 'برشلونة', en: 'Barcelona', code: 'BCN', country: 'Spain' },
  { ar: 'إشبيلية', en: 'Seville', code: 'SVQ', country: 'Spain' },
  { ar: 'إسطنبول', en: 'Istanbul', code: 'IST', country: 'Turkey' },
  { ar: 'روما', en: 'Rome', code: 'ROM', country: 'Italy' },
  { ar: 'باريس', en: 'Paris', code: 'PAR', country: 'France' },
  { ar: 'لندن', en: 'London', code: 'LON', country: 'UK' },
  { ar: 'برلين', en: 'Berlin', code: 'BER', country: 'Germany' },
  { ar: 'أمستردام', en: 'Amsterdam', code: 'AMS', country: 'Netherlands' },
  { ar: 'فيينا', en: 'Vienna', code: 'VIE', country: 'Austria' },
  { ar: 'براغ', en: 'Prague', code: 'PRG', country: 'Czech Republic' },
  { ar: 'بودابست', en: 'Budapest', code: 'BUD', country: 'Hungary' },
  { ar: 'وارسو', en: 'Warsaw', code: 'WAW', country: 'Poland' },
  { ar: 'زيورخ', en: 'Zurich', code: 'ZUR', country: 'Switzerland' },
  { ar: 'جنيف', en: 'Geneva', code: 'GVA', country: 'Switzerland' },
  { ar: 'ميلان', en: 'Milan', code: 'MIL', country: 'Italy' },
  { ar: 'فلورنسا', en: 'Florence', code: 'FLR', country: 'Italy' },
  { ar: 'البندقية', en: 'Venice', code: 'VCE', country: 'Italy' },
  { ar: 'أثينا', en: 'Athens', code: 'ATH', country: 'Greece' },
  { ar: 'لشبونة', en: 'Lisbon', code: 'LIS', country: 'Portugal' },
  { ar: 'بورتو', en: 'Porto', code: 'OPO', country: 'Portugal' },
  { ar: 'ستوكهولم', en: 'Stockholm', code: 'STO', country: 'Sweden' },
  { ar: 'كوبنهاغن', en: 'Copenhagen', code: 'CPH', country: 'Denmark' },
  { ar: 'أوسلو', en: 'Oslo', code: 'OSL', country: 'Norway' },
  { ar: 'هلسنكي', en: 'Helsinki', code: 'HEL', country: 'Finland' },
  { ar: 'بروكسل', en: 'Brussels', code: 'BRU', country: 'Belgium' },
  { ar: 'دبلن', en: 'Dublin', code: 'DUB', country: 'Ireland' },
  { ar: 'إدنبرة', en: 'Edinburgh', code: 'EDI', country: 'Scotland' },
  { ar: 'مانشستر', en: 'Manchester', code: 'MAN', country: 'UK' },
  { ar: 'ليون', en: 'Lyon', code: 'LYS', country: 'France' },
  { ar: 'نيس', en: 'Nice', code: 'NCE', country: 'France' },
  { ar: 'مرسيليا', en: 'Marseille', code: 'MRS', country: 'France' },
  { ar: 'مونيخ', en: 'Munich', code: 'MUC', country: 'Germany' },
  { ar: 'فرانكفورت', en: 'Frankfurt', code: 'FRA', country: 'Germany' },
  { ar: 'هامبورغ', en: 'Hamburg', code: 'HAM', country: 'Germany' },
  
  // Saudi departure cities only
  { ar: 'الرياض', en: 'Riyadh', code: 'RUH', country: 'Saudi Arabia' },
  { ar: 'جدة', en: 'Jeddah', code: 'JED', country: 'Saudi Arabia' },
  { ar: 'الدمام', en: 'Dammam', code: 'DMM', country: 'Saudi Arabia' }
];
