// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkmycgoowmelysnohssi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbXljZ29vd21lbHlzbm9oc3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTU3NTQsImV4cCI6MjA2Mzc5MTc1NH0.erQ7TMQy5yUnU6oBjF54KEzySEUwq2l_B-HQ8YxYcaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);